import { chromium } from 'playwright';
import fs from 'node:fs';
const base='http://127.0.0.1:4173';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const errors=[];
const page=await browser.newPage({viewport:{width:1280,height:900}});
page.on('console',m=>m.type()==='error'&&errors.push(m.text())); page.on('pageerror',e=>errors.push(e.message));
await page.goto(base,{waitUntil:'networkidle'}); await page.evaluate(()=>document.fonts.ready);
const desktop={title:await page.title(),overflow:await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),projects:await page.locator('.project-row').count(),links:await page.locator('a[href]').count(),cv:await page.locator('a[href="/arjun-kh-cv.pdf"]').count(),behance:await page.locator('a[href*="behance"]').count()};
await page.screenshot({path:'/tmp/mfg-app-preview/arjun-anti-portfolio/cv-desktop.png'});
await page.locator('.open-command').first().focus(); await page.keyboard.press('Enter'); await page.waitForTimeout(250);
const detail={path:new URL(page.url()).pathname,heading:await page.locator('.detail-intro h1').innerText(),overflow:await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),status:await page.locator('.detail-kicker').innerText()};
await page.reload({waitUntil:'networkidle'}); const direct={visible:await page.locator('.detail-page').isVisible(),heading:await page.locator('.detail-intro h1').innerText()};
await page.keyboard.press('Escape'); await page.waitForTimeout(100);
const cvRes=await page.request.get(base+'/arjun-kh-cv.pdf'); const asset={status:cvRes.status(),type:cvRes.headers()['content-type'],bytes:(await cvRes.body()).length};
const mobile=await browser.newPage({viewport:{width:390,height:844}}); mobile.on('pageerror',e=>errors.push(e.message)); await mobile.goto(base,{waitUntil:'networkidle'}); await mobile.evaluate(()=>document.fonts.ready); await mobile.locator('.mobile-menu').click(); const mobileCheck={overflow:await mobile.evaluate(()=>document.documentElement.scrollWidth-innerWidth),menuVisible:await mobile.locator('.mobile-nav').isVisible(),items:await mobile.locator('.mobile-nav button').count()}; await mobile.screenshot({path:'/tmp/mfg-app-preview/arjun-anti-portfolio/cv-mobile.png'});
const reduced=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}); await reduced.goto(base,{waitUntil:'networkidle'}); const reducedCheck=await reduced.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior);
const tinyTargets=await page.locator('a,button').evaluateAll(els=>els.map(el=>({text:(el.textContent||'').trim().slice(0,30),w:el.getBoundingClientRect().width,h:el.getBoundingClientRect().height})).filter(x=>x.w>0&&x.h>0&&(x.w<44||x.h<44)));
console.log(JSON.stringify({desktop,detail,direct,asset,mobileCheck,reducedCheck,tinyTargets,errors},null,2));
await browser.close();
